apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-hello-world
  template:
    metadata:
      labels:
        app: k8s-hello-world
    spec:
      containers:
      - name: k8s-hello-world
        image: adelll/k8s-hello-world
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
